M48
; DRILL file {KiCad 9.0.5} date 2026-06-27T07:24:10+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-27T07:24:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X149.4Y-108.6
X149.4Y-128.6
X172.1Y-108.6
X172.1Y-128.6
M30
